language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
    - DJANGO=2.1
    - DJANGO=2.2

install:
    - pip install --upgrade pip
    - pip install -r requirements/test.txt
    - pip install Django==$DJANGO
    - pip install .
script:
  - pytest

sudo: false
